### ISSUE TITLE
Defining a class on a trns

### ISSUE THREAD

**Issue by lehresman** [linjunpop/riif#11]
How do I define a class on a trns?  Looking through the code, it looks like I should do it like:

```
iif.trns do
  row do
    class "something"
  end
end
```

But that obviously throws syntax errors.  I tried using 'klass' as the readme suggests, but there doesn't appear to be support for that.  Any suggestions?

**Comment by linjunpop** [comment]
Just released v0.7.0. this should be fixed.

Tha dsl should be

```ruby
iif.trns do
  row do
    klass "something"
  end
end
```
