### ISSUE TITLE
Cannot pass instance variable from controller to iif.riif

### ISSUE THREAD

**Issue by shloimeweinberger** [linjunpop/riif#33]
Hi,

This gem looks great, however i'm having a hard time figuring out how to pass an instance variable from the controller to the iff.riff file. The idea is to cycle through an array of hashes, and the iif output should have the correct values.

Any help is appreciated.

**Comment by linjunpop** [comment]
You can checkout https://github.com/linjunpop/riif/blob/ae42dc8079bfcc8958d132c0ab792821ace50c21/spec/internal/app/controllers/invoices_controller.rb#L5

**Comment by linjunpop** [comment]
Gonna close this issue, if this does not fix. Please reopen this. :)
