### ISSUE TITLE
layout: false not being respected

### ISSUE THREAD

**Issue by climbingblake** [linjunpop/riif#36]
thanks for the gem!
Im seeing an odd behaviour.
`respond_to do |format|
      format.iif { render iif: render_to_string, filename: 'batman' }
      format.html
    end
`
downloads a "batman" file, but with the entire application.haml layout, along with the IIF data in teh yield section

So I tried to set layout:false

`respond_to do |format|
      format.iif { render iif: render_to_string, filename: 'batman', layout: false }
      format.html
    end
`
Im still seeing the application.haml layout , with the IIF data in the yield.  so in essence, its creating a .html page and downloading it as "batman.iif"  

If I remove the iif: render_to_string

`    respond_to do |format|
      format.iif { render filename: 'batman', layout: false }
      format.html
    end
`
I get the expected  file output, but now the filename is the ID of the record, not "batman".

So im wondering if the layout: false is necessary, as Im not seeing it anywhere in the docs or other users examples.

Thanks for any info.

**Comment by linjunpop** [comment]
I tested on a Rails 5.1.5 app, and it works fine with:

```ruby
    respond_to do |format|
      format.iif {
        render iif: render_to_string,
        filename: 'batman'
      }
    end
```

Can you post more details? Or an example app to reproduce the error is better. :)

**Comment by climbingblake** [comment]
many thanks !   here is what I have.

#console upon request
`app/controllers/transactions_controller.rb:26:in `show'
Started GET "/users/1/transactions/1.iif" for 127.0.0.1 at 2018-03-24 11:43:29 -0400
Processing by TransactionsController#show as IIF
  Parameters: {"user_id"=>"1", "id"=>"1"}
  User Load (0.6ms)  SELECT  `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = 1 ORDER BY `users`.`id` ASC LIMIT 1
  Transaction Load (0.6ms)  SELECT  `transactions`.* FROM `transactions` WHERE `transactions`.`deleted_at` IS NULL AND `transactions`.`id` = 1 LIMIT 1
  User Load (1.5ms)  SELECT  `users`.* FROM `users` WHERE `users`.`deleted_at` IS NULL AND `users`.`id` = 1 LIMIT 1
  Rendering transactions/show.iif.riif within layouts/application
  Rendered transactions/show.iif.riif within layouts/application (1.7ms)
  Rendered partials/_header.haml (40.3ms)
  RailsSettings::SettingObject Load (1.2ms)  SELECT `settings`.* FROM `settings` WHERE `settings`.`target_id` = 1 AND `settings`.`target_type` = 'User'
  Rendered partials/_sidebar_dashboard_list.haml (10.9ms)
  Rendered partials/_sidebar.haml (124.0ms)
  Rendered partials/_session_expiration_modal.haml (7.2ms)
  Rendering text template
  Rendered text template (0.0ms)
Sent data batman.iif (3.5ms)
Completed 200 OK in 428ms (Views: 3.8ms | ActiveRecord: 8.6ms)`

#transactions_controller
`# GET /transactions/1
  # GET /transactions/1.json
  def show
    add_breadcrumb @user.name_and_id, user_path(@user)
    add_breadcrumb "Users Transactions", user_transactions_path(@user)
    respond_to do |format|
      format.iif {render iif: render_to_string, filename: 'batman'}
      format.html
    end
  end`

batmain.iif is downloaded and contains the full html of the application layout, with the correct exported data in the main <%= yield %>

thanks for any info or insight. I would just assume forcing layout: false would work but now im seeing that it your gem should default to that.

**Comment by climbingblake** [comment]
any additional ideas about this?
